### ISSUE TITLE
Cluster Creation Automation

### ISSUE THREAD

**Issue by sween** [intersystems-community/sam#1]
Is there any way yet to automate or programmatically add cluster/instance information to SAM?

**Comment by zrml** [comment]
Sorry I'm late on this one @sween; You must have noticed the SAM Manager API.
Docs:
https://docs.intersystems.com/sam/csp/docbook/Doc.View.cls?KEY=RSAPI_overview
An example:
https://github.com/intersystems-community/icm-sam-1
the actual curl calls to be more precise: 
https://github.com/intersystems-community/icm-sam-1/blob/master/SAM-populate.sh
